### ISSUE TITLE
feat: 2024.3 plugin

### ISSUE THREAD

**Issue by MaikPeters1511** [Unthrottled/AMII#184]
### Your Environment

new version 

### How to reproduce.

Step One: Open Project

### What is expected?

To show up when the project started.

**Comment by Unthrottled** [comment]
its on my list!

**Comment by MaikPeters1511** [comment]
thx cool

**Comment by CXwudi** [comment]
I am wakuwaku waiting
![image](https://i1.sndcdn.com/artworks-JkEnzqAiOGOl9VYZ-XSvdRQ-t500x500.jpg)

**Comment by Unthrottled** [comment]
you are able to manually install the plugin now

https://github.com/ani-memes/AMII?tab=readme-ov-file#installation

will be a while before I get it out to the jetbrains marketplace

**Comment by MaikPeters1511** [comment]
vielen danke super gemacht
